# Generated by Django 5.0.6 on 2024-07-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner_subscription"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payments_date"],
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_amount",
            new_name="payment_sum",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="pay_day",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="идентификатор платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payments_date",
            field=models.DateTimeField(auto_now=True, verbose_name="дата оплаты"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="город"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "наличные"), ("card", "банковский перевод")],
                default="card",
                max_length=50,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/", verbose_name="аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="телефон"
            ),
        ),
    ]
